### PR TITLE
feat: add support for channel parameters

### LINKED ISSUE #345: Support parameter for channel
#### Reason/Context
This is long missed feature of template to support [`parameter`s for channel object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#parametersObject).

#### Description
Support of `parameter`s should be introduced for all protocols currently supported by template (kafka, mqtt, amqp).
Changes required in following files:
- [AmqpPublisher.java](https://github.com/asyncapi/java-spring-template/blob/7053fd18445ed9ff63784816ec959b57bb958395/partials/AmqpPublisher.java)
- [KafkaPublisher.java](https://github.com/asyncapi/java-spring-template/blob/7053fd18445ed9ff63784816ec959b57bb958395/partials/KafkaPublisher.java)
- [MqttConfig.java](https://github.com/asyncapi/java-spring-template/blob/7053fd18445ed9ff63784816ec959b57bb958395/partials/MqttConfig.java)
- [MessageHandlerService.java](https://github.com/asyncapi/java-spring-template/blob/7053fd18445ed9ff63784816ec959b57bb958395/template/src/main/java/com/asyncapi/service/MessageHandlerService.java)

1. General support:
To support in kafka follow to reference doc, [RoutingKafkaTemplate](https://docs.spring.io/spring-kafka/docs/current/reference/html/#routing-template) to send, [containerFactory](https://docs.spring.io/spring-kafka/docs/current/reference/html/#record-listener) to receive.
To support in amqp follow to reference doc [topic exchange](https://www.cloudamqp.com/blog/part4-rabbitmq-for-beginners-exchanges-routing-keys-bindings.html#topic-exchange)
To support in mqtt follow to reference doc, [topicExpression](https://docs.spring.io/spring-integration/api/org/springframework/integration/mqtt/outbound/AbstractMqttMessageHandler.html#setTopicExpression(org.springframework.expression.Expression)) to receive and send, to send MessageHandler also should be adopted.

3. Arbitrary methods
Parametrized methods should be provided, e.g. for channel `lights/{roomName}/{sensorID}` method like
```
public void <operationName>(String roomName, Integer sensorID, Message payload)
```

### LINKED ISSUE #358: AmqpConfig.java file has syntax errors
#### Describe the bug
queues() method of AmqpConfig.java class missing a big parantheses "}"

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:
ag asyncapi.yaml  @asyncapi/java-spring-template 

- Screenshots
N/A
- Link to GitHub repository with project that has issues
https://github.com/asyncapi/java-spring-template/blob/master/partials/AmqpConfig.java

- Files that can help reproduce the issue, like your AsyncAPI file, either paste inside the issue in a code block or in a sharable [gist](https://gist.github.com/)
[report.pdf](https://github.com/asyncapi/java-spring-template/files/13578888/report.pdf)

#### Expected behavior
Fix the bug

### PR DESCRIPTION
**Pull request by Tenischev**
**Description**

details in #345

General support:

- [x] kafka
- [x] mqtt
- [x] amqp

Arbitrary methods:

- [x] kafka
- [x] mqtt
- [x] amqp

**Related issue(s)**
Resolves #345
Resolves #358

### CODE REVIEW

**Review by derberg — COMMENTED** [review]
LGTM, but shouldn't we have a proper mention in the readme?

**Comment by Tenischev** [comment]
List of missing features are updated, also add attention bar about v3 support

**Review by derberg — APPROVED** [review]
LGTM

**Comment by aeworxet** [comment]
@asyncapi/bounty_team

**Pull request merged**
