### PR TITLE
feat!: update template for spring boot 3

### LINKED ISSUE #296: JavaBeans format for lists not compliant, causes failures with spring boot 3.0.2 when validation of list is added
#### Describe the bug
When generating a list, the tool adds the suffix 'List', but Java Beans validation in spring boot 3.0.2 relies on full compliance to specifications by using reflection, then the name of fields and the getters should be aligned.
Current behaviour:
field: aliases
generated as: aliasesList
getter: getAliases
compliant to JavaBeans specs: no
 
Safe behavious
field: aliases
generated as: aliases
getter: getAliases
compliant to JavaBeans specs: yes

#### How to Reproduce
In spring boot 3.*, try to generate a kafka topic model with validation of a List annotated with @NotNull.
When validation will run, an IllegalStateException will be raised

#### Expected behavior
The field should be generated without the 'List' suffix in compliance with JavaBeans specification. 
( problem is at $$message$$ lines 42 and $$objectSchema$$ lines 24, 26,28,97,127,157,163,169 - I cannot contribute due to company policies )

### LINKED ISSUE #297: Please add a parameter ( jakartaForKafkaValidation? ) to support both javax.validation and jakarta.validation packages
#### Reason/Context
While using the generator with spring boot 3.*, the imports will fail as the package javax.validation has been renamed to jakarta.validation

#### Description
Please try answering few of those questions
- What changes have to be introduced?
1. add the following code to the parameters of package.json (or pick a better naming): 
``` 
"jakartaForKafkaValidation": {
        "description": "To check if the target framework will leverage on javax.validation or jakarta.validation package for kafka",
        "default": "false",
        "required": false
      }
```
3. in $$message$$.java replace the import of javax.validation with
```
{% if params.jakartaForKafkaValidation === 'false' %}
import javax.validation.Valid;
{% else %}
import jakarta.validation.Valid;
{% endif %}
```
4. in $$onjectSchema$$.java replace the import of javax.validation with:
```
{% if params.jakartaForKafkaValidation === 'false' %}
import javax.validation.constraints.*;
import javax.validation.Valid;
{% else %}
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
{% endif %}
```

- Will this be a breaking change?
not with a safe default
- How could it be implemented/designed?
please see my previous answers: note that is an advise as I do not know in detail the templating engine. Sadly I cannot contribute due to company policies

### LINKED ISSUE #318: Upgrade the code generated to Spring Boot 3
Reviewing the example, I noticed that the code generated is for: 

```
springBootVersion=2.2.6.RELEASE
springDependencyManager=1.0.9.RELEASE
```

It could be interesting to upgrade the code to spring boot 3.0
https://spring.io/projects/spring-boot#support

Juan Antonio

### PR DESCRIPTION
**Pull request by Tenischev**
**Description**

Since spring boot 3 released some adjustments are required across template
- switch from javax to jakarta validation according to [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes#third-party-library-upgrades) 
- update KafkaHeaders with according of changes in [Spring Kafka 3](https://docs.spring.io/spring-kafka/docs/current/reference/html/#x30-headers)
- strict rules for get/set methods which reported in #296

For backward compatibility and users sake parameter `springBoot2` created. 

**Related issue(s)**
Resolves #296 
Resolves #297 
Resolves #318

### CODE REVIEW

**Review by jbiscella — COMMENTED** [review]
Please note that if you remove 'List' at the end of line 29, 31, 33

you remove + 'List' at line 102, 132 , 162, 168 and 174

you would fix the bug raised as per https://github.com/asyncapi/java-spring-template/issues/296

To reproduce the bug you can add the @NotNull annotation to a list and execute the validation

**Comment by jbiscella** [comment]
Also wondering if could be a sensible advise to add the @Generated annotation to all the classes to ease configuring sonar to exclude them from the checks... could be a separate feature request probably

https://docs.oracle.com/javase/8/docs/api/javax/annotation/Generated.html

**Comment by Tenischev** [comment]
Hi @jbiscella 
I would not address `@generated` in this PR, because intention of this PR is to support spring boot 3.
Support of `@generated` will be made in a separate PR

**Comment by derberg** [comment]
shouldn't this be `feat!` to release 1.0? you have a fallback flag, yes, but still it must be explicitly set

**Comment by Tenischev** [comment]
> shouldn't this be `feat!` to release 1.0? you have a fallback flag, yes, but still it must be explicitly set

Yes, makes sense

**Review by derberg — APPROVED** [review]

**Pull request merged**
